server:
  port: 30030
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:hsql://localhost:9013/templateDB
    username: SA
    password:

logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace